version: "3"
services:
    gitea:
        image: kunde21/gitea-arm:latest
        restart: always
        ports:
            - "2222:22"
        volumes:
            - ./gitea:/data
            - ./gitea-app.ini:/data/gitea/conf/app.ini
        labels:
            - traefik.backend=gitea
            - traefik.frontend.rule=Host:10.1.1.2
            # You can specify path prefix for gitea, set
            # to / if you don't want to use path prefix.
            - traefik.frontend.rule=PathPrefixStrip:/git
            - traefik.frontend.entryPoints=http
            - traefik.docker.network=gitea-network
            - traefik.port=3000

    drone:
        image: drone/drone:linux-arm
        restart: always
        depends_on:
            - gitea
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./drone:/var/lib/drone
        environment:
            - DRONE_GITEA_SERVER=http://gitea:3000
            - DRONE_GIT_ALWAYS_AUTH=false
            - DRONE_SERVER_HOST=10.1.1.2:81
            - DRONE_RUNNER_CAPACITY=2
            - DRONE_SERVER_PROTO=http
            - DRONE_TLS_AUTOCERT=false
            - DRONE_NETWORK=gitea-network
            - DRONE_SECRET=DRONE_SECRETs
            - DRONE_USER_CREATE=username:git,admin:true
            - DRONE_ADMIN=git
        labels:
            - traefik.backend=drone
            - traefik.frontend.rule=Host:10.1.1.2
            - traefik.frontend.rule=PathPrefixStrip:/
            - traefik.frontend.entryPoints=drone
            - traefik.docker.network=gitea-network
            - traefik.port=80
    drone-agent:
        image: drone/agent:linux-arm
        command: agent
        restart: always
        depends_on:
            - drone
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DRONE_SERVER=drone:9000
            - DRONE_SECRET=DRONE_SECRETs
            - DOCKER_ARCH=arm
            - DRONE_ADMIN=git
    reverse-proxy:
        image: traefik
        restart: always
        command: --api --docker
        links:
            - gitea
            - drone
        ports:
            - "80:80" # for Gitea
            - "81:81" # for Drone
            - "8081:8080" # for Traefik Web UI
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik:/etc/traefik

networks:
  default:
    external:
      name: gitea-network
